### PR TITLE
Fix popup closing issue

### LINKED ISSUE #426: Reopen reef popup if marker changes due to offset
Steps to replicate:
1. Open the aqualink map
2. search `Dux`
3. Click the first option (takes you to a reef near the left edge of USA)
4. Once the pan animation ends, the popup closes unexpectedly. 

-- find a way to stop the popup from closing pre-maturely.

### PR DESCRIPTION
**Pull request by Ry-DS**
Closes #426
Disables `Popup`'s auto opening `useEffect` if the marker its applied on isn't the original marker (its an offset)

test: http://aqua-popup.surge.sh

### CODE REVIEW

**Comment by tleraj** [comment]
I am a little suspicious because using Leaflet's `"moveend"` event was causing problems in the past. I'm not 100% sure that it causes problems now, but seeing it again brings me a little anxiety :stuck_out_tongue:

File: packages/website/src/routes/HomeMap/Map/Popup/index.tsx [hunk 1]
```diff
@@ -37,7 +38,18 @@ const Popup = ({ reef, classes }: PopupProps) => {
...
+      const moveFunc = () => {
+        const point: LatLngTuple = [lat, lng];
+        popup.setLatLng(point).openOn(map);
+        map.off("moveend", moveFunc);
+      };
+      moveFunc();
+      // If the map is zoomed out (we can possibly see repeat markers) then we should reopen the popup.
+      // There's a good chance it might close on moveend (pan animation finishes) - a small quirk of Leaflet
+      // when we have markers outside of the normal map range.
+      // Closest instance I could find in the wild: https://stackoverflow.com/a/30135133/5279269
```
Comment (ericboucher) [inline packages/website/src/routes/HomeMap/Map/Popup/index.tsx:51]: The other option is to wait until the end of the zoom event before opening the popup. This way you only have to open it once. No?

File: packages/website/src/routes/HomeMap/Map/Markers/index.tsx [hunk 2]
```diff
@@ -44,11 +44,40 @@ const clusterIcon = (cluster: any) => {
   });
 };
 
+function MarkerWithPopup({
```
Comment (ericboucher) [inline packages/website/src/routes/HomeMap/Map/Markers/index.tsx:47]: this doesn't feel super necessary to have as a standalone function

**Review by ericboucher — APPROVED** [review]
