### PR TITLE
Display Spotter Data

### LINKED ISSUE #350: Bugs on Mobile Version
Bugs reported by @ericboucher:
- [x] 1. When you click on a reef on the map and open a new reef page, it very often does not load properly and shows “No data” and stays this way. I investigated a bit and I think that it’s because “loading” is set to false and the mobile processing is too slow to catch the change. If you reload the page it works fine. This is obviously not the expected behavior….

 - [x] 2. If you play around on the map, especially around sites that have overlapping pin and click in the overlapping zone a few times, the app crashes on mobile. I was not able to reproduce on desktop. Might have something to do with the touch on mobile trying to send update requests for two competing markers. I was able to reproduce the bug using the mobile dev test mode on chrome desktop

<details>
  <summary>Stacktrace</summary>
  
  ```javascript
index.js:1 The above error occurred in the <Popup> component:
    in Popup (created by Context.Consumer)
    in ForwardRef(Leaflet(Popup)) (at Popup/index.tsx:32)
    in Popup (created by WithStyles(Popup))
    in WithStyles(Popup) (at Markers/index.tsx:113)
    in Marker (created by Context.Consumer)
    in ForwardRef(Leaflet(Marker)) (at Markers/index.tsx:100)
    in MarkerClusterGroup (created by Context.Consumer)
    in ForwardRef(Leaflet(MarkerClusterGroup)) (at Markers/index.tsx:90)
    in LayerGroup (created by Context.Consumer)
    in ForwardRef(Leaflet(LayerGroup)) (at Markers/index.tsx:89)
    in ReefMarkers (at Map/index.tsx:62)
    in div (created by Map)
    in Map (at Map/index.tsx:50)
    in HomepageMap (created by WithStyles(HomepageMap))
    in WithStyles(HomepageMap) (at HomeMap/index.tsx:39)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (at HomeMap/index.tsx:38)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (at HomeMap/index.tsx:37)
    in div (at HomeMap/index.tsx:36)
    in Homepage (created by WithStyles(Homepage))
    in WithStyles(Homepage) (created by Context.Consumer)
    in Route (at App/index.tsx:49)
    in Switch (at App/index.tsx:47)
    in div (at App/index.tsx:45)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App/index.tsx:44)
    in ThemeProvider (at App/index.tsx:43)
    in App (at src/index.tsx:37)
    in Provider (at src/index.tsx:36)
Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
  ```
  
</details>

Screenshots: 

1                                    |  2                                  |  3
:-------------------------:|:-------------------------:|:-------------------------:
Image from iOS    |  Image from iOS (1) | Image from iOS

### PR DESCRIPTION
**Pull request by tleraj**
The purpose of this PR is to display data coming from the Smart Buoy on a chart.

Screen Shot 2020-10-28 at 6 19 39 PM

TODO: 
- [x] On the “One Day” chart, make sure the daillyData.satelliteTemp (called surfaceTemperature) is also visible even if it is just a line with the latest value.
- [x] Add an endDate selector next to the time range selector
- [x] Fix tooltip in `One Day` so surface temp is shown - hidden if data doesn't exist for given day
- [x] Filter Daily data in `utils.ts` so yaxis limits are done correctly

Also closes #350 via https://github.com/aqualinkorg/aqualink-app/pull/337/commits/dcd6138fbd392138feb796de220e68ffc2eff793

### CODE REVIEW

File: packages/website/src/common/Chart/Tooltip/index.tsx [hunk 1]
```diff
@@ -51,32 +73,39 @@ const Tooltip = ({
...
-                </Grid>
-              </Grid>
+              {spotterSurfaceTemp &&
+                TemperatureMetric(
+                  spotterSurfaceTemp,
+                  "TEMP AT 1m",
+                  surfaceTemperature ? 6 : 12,
+                  classes.tooltipContentItem
+                )}
+              {!spotterSurfaceTemp &&
```
Comment (SimplyBallistic) [inline packages/website/src/common/Chart/Tooltip/index.tsx:83]: TODO compress 83 with 99

File: packages/website/src/common/Chart/utils.ts [hunk 2]
```diff
@@ -180,3 +275,40 @@ export const createChartData = (
   }
   return data;
 };
+
+export function sameDay(date1: string | number, date2: string | number | Date) {
+  const d1 = new Date(date1);
+  const d2 = new Date(date2);
+  return (
+    d1.getFullYear() === d2.getFullYear() &&
```
Comment (SimplyBallistic) [inline packages/website/src/common/Chart/utils.ts:283]: Could use to date string here

File: packages/website/src/common/SelectRange/index.tsx [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+  );
+};
+
+interface SelectRangeProps {
+  open: boolean;
+  value: Range;
+  width: GridSize;
+  onClose: () => void;
+  onOpen: () => void;
+  onRangeChange: (event: ChangeEvent<{ value: unknown }>) => void;
```
Comment (SimplyBallistic) [inline packages/website/src/common/SelectRange/index.tsx:60]: TODO investigate unknown type

File: packages/website/src/helpers/dates.ts [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+
+export const subtractFromDate = (endDate: string, amount: Range): string => {
+  const date = new Date(endDate);
+  const day = 1000 * 60 * 60 * 24;
+  switch (amount) {
+    case "day":
+      return new Date(date.setTime(date.getTime() - 1 * day)).toISOString();
+    case "week":
+      return new Date(date.setTime(date.getTime() - 7 * day)).toISOString();
+    default:
```
Comment (SimplyBallistic) [inline packages/website/src/helpers/dates.ts:12]: Line could be removed with rearranged cases

File: packages/website/src/helpers/dates.ts [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+
+  return sortedData[0].date;
+};
+
+export const findChartPeriod = (range: Range) => {
+  switch (range) {
+    case "day":
+      return "hour";
+    case "week":
+      return "day";
```
Comment (SimplyBallistic) [inline packages/website/src/helpers/dates.ts:39]: Same as 12

File: packages/website/src/routes/ReefRoutes/Reef/ReefDetails.tsx [hunk 6]
```diff
@@ -1,13 +1,16 @@
-import React, { ElementType } from "react";
+/* eslint-disable no-nested-ternary */
```
Comment (SimplyBallistic) [inline packages/website/src/routes/ReefRoutes/Reef/ReefDetails.tsx:1]: TODO move to site

File: packages/website/src/routes/ReefRoutes/Reef/index.tsx [hunk 7]
```diff
@@ -110,11 +118,44 @@ const Reef = ({ match, classes }: ReefProps) => {
 
   const hasDailyData = Boolean(dailyData && dailyData.length > 0);
 
+  const spotterData = useSelector(reefSpotterDataSelector);
+  const [range, setRange] = useState<Range>("week");
+  const today = new Date();
+  const todayDate = new Date(
```
Comment (SimplyBallistic) [inline packages/website/src/routes/ReefRoutes/Reef/index.tsx:124]: TODO simplify

File: packages/website/src/routes/Surveys/View/index.tsx [hunk 8]
```diff
@@ -1,4 +1,5 @@
-import React, { useEffect } from "react";
+/* eslint-disable no-nested-ternary */
```
Comment (SimplyBallistic) [inline packages/website/src/routes/Surveys/View/index.tsx:1]: Move to site

File: packages/website/src/routes/Surveys/View/index.tsx [hunk 9]
```diff
@@ -113,8 +159,53 @@ const SurveyViewPage = ({ reef, surveyId, classes }: SurveyViewPageProps) => {
...
+                    alignItems="center"
+                    justifyContent="center"
+                    textAlign="center"
+                    p={4}
+                  >
+                    <CircularProgress size="6rem" thickness={1} />
+                  </Box>
+                ) : spotterData && endDate ? (
+                  <>
+                    <Grid container alignItems="center" item xs={11}>
```
Comment (SimplyBallistic) [inline packages/website/src/routes/Surveys/View/index.tsx:188]: Repeat from reefs page. TODO investigate if possible to merge

File: packages/website/src/store/Reefs/selectedReefSlice.ts [hunk 10]
```diff
@@ -116,6 +179,11 @@ export const reefLoadingSelector = (
   state: RootState
 ): SelectedReefState["loading"] => state.selectedReef.loading;
 
+export const reefspotterDataLoadingSelector = (
```
Comment (SimplyBallistic) [inline packages/website/src/store/Reefs/selectedReefSlice.ts:182]: Casing

**Review by SimplyBallistic — CHANGES_REQUESTED** [review]

File: packages/website/src/routes/ReefRoutes/Reef/ReefDetails.tsx [hunk 11]
```diff
@@ -180,7 +177,7 @@ const ReefDetails = ({
               spotterData && (
                 <Charts
                   title="HOURLY WATER TEMPERATURE (°C)"
-                  dailyData={filteredDailyData}
```
Comment (SimplyBallistic) [inline packages/website/src/routes/ReefRoutes/Reef/ReefDetails.tsx]: @tleraj wondering what `filteredDailyData` was for? After replacing it with the full set, the x axis still works fine since axis limits is calculated strongly by spotter data.

Comment (tleraj) [reply packages/website/src/routes/ReefRoutes/Reef/ReefDetails.tsx]: It had more to do with the yAxis limits. In order to calculate the yAxis limits we only need to consider the data inside the `[startDate, endDate]` time window. I thought we don't want any data outside this window to affect the yAxis limits calculation.

File: packages/website/src/common/Chart/index.tsx [hunk 12]
```diff
@@ -170,13 +186,13 @@ function Chart({
                 week: "MMM D",
                 month: "MMM",
               },
-              unit: xPeriod,
+              unit: chartPeriod || xPeriod,
             },
             display: true,
             ticks: {
               labelOffset: xTickShift,
               min: xAxisMin,
```
Comment (tleraj) [inline packages/website/src/common/Chart/index.tsx:194]: Shouldn't this also be `min: startDate || xAxisMin`?

Comment (ericboucher) [reply packages/website/src/common/Chart/index.tsx:194]: If we are doing the filtering properly it should be pretty much the same thing and it ensures that we have a clean start

File: packages/website/src/routes/ReefRoutes/Reef/ReefDetails.tsx (hunk 11 above)
Comment (SimplyBallistic) [reply packages/website/src/routes/ReefRoutes/Reef/ReefDetails.tsx]: Ahh I see! I'll move this to the utils file, think it's better to try do all this processing in one place in a coherence sense. Shouldn't be too hard since we pass start date and end date to chart

File: packages/website/src/common/Chart/index.tsx (hunk 12 above)
Comment (SimplyBallistic) [reply packages/website/src/common/Chart/index.tsx:194]: Would that mean `endDate || xAxisMax` is also not needed? Tried removing it and the chart functioned the same. What cases might `endDate` here be used?

Comment (ericboucher) [reply packages/website/src/common/Chart/index.tsx:197]: Yeah that's probably fine I think

**Review by SimplyBallistic — APPROVED** [review]

File: packages/website/src/common/Chart/Tooltip/index.tsx [hunk 13]
```diff
@@ -33,6 +64,7 @@ const Tooltip = ({
           title={
             <Typography color="textPrimary" variant="caption">
               {dateString}
+              {spotterSurfaceTemp ? " UTC" : ""}
```
Comment (SimplyBallistic) [inline packages/website/src/common/Chart/Tooltip/index.tsx:67]: Maybe `{spotterSurfaceTemp && " UTC"}` might work here?

File: packages/website/src/common/Chart/Tooltip/index.tsx [hunk 14]
```diff
@@ -9,12 +9,41 @@ import {
...
+    marginTop: 3,
+    width: size,
+    height: size,
+    borderRadius: size / 2,
+    backgroundColor,
+    display: "inline-block",
+  })
+);
+
+const TemperatureMetric = (
```
Comment (SimplyBallistic) [inline packages/website/src/common/Chart/Tooltip/index.tsx:28]: Converting this to a component might be the best. Otherwise it works fine :)

File: packages/website/src/common/Chart/index.tsx [hunk 15]
```diff
@@ -170,13 +189,13 @@ function Chart({
...
-              max: xAxisMax,
+              max: endDate || xAxisMax,
```
Comment (SimplyBallistic) [inline packages/website/src/common/Chart/index.tsx:198]: TODO remove

**Comment by SimplyBallistic** [comment]
The survey chart and reef details chart are very similar, should we make a component to combine them?
| Reef Details | Surveys |
| ------------- | ------------- |
| image | image |

Also, survey charts look broken

File: packages/website/src/common/Chart/index.tsx (hunk 15 above)
Comment (SimplyBallistic) [inline packages/website/src/common/Chart/index.tsx:198]: The survey chart acts strangely without this check, since there's no spotter data for 5th August (and limits can't be calculated without). I say keep it for now...
